// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class AddNewsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  //媒体ID，凤凰令牌
  private Integer ids=503862;
  //遍历次数
  private int num=14;
  //媒体名称
  private String[] mediaName={
//
//          //-----------------------------------
//           "内江新闻网", "乐山日报",
//          //-----------------------------------
//          "三江都市报", "乐山新闻网", "资阳日报",
//          //-----------------------------------
//          "资阳网", "宜宾日报", "宜宾晚报",
//          //-----------------------------------
//          "金江网", "宜宾新闻网", "南充日报", "南充新闻网",
//  //-----------------------------------
            "南充晚报","达州日报","达州日报网",
    //-----------------------------------
            "达州晚报","雅安日报","大雅网",
    //-----------------------------------
            "北纬网","广安日报","广安在线",
    //-----------------------------------
            "广安新闻网",
    //-----------------------------------
            "巴中传媒网","眉山日报","眉山网","东坡文化网"

  };
  //网站url
  private String[] url={
/*                  "http://www.scnjnews.com/",
                  "http://www.cnepaper.com/lsrb/html/{year}-{month2}/{day2}/node_1.htm",
          //-----------------------------------
                  "http://www.cnepaper.com/sjdsb/html/{year}-{month2}/{day2}/node_1.htm",
                  "http://www.leshan.cn/",
                  "http://paper.zyrb.com.cn/html/http://ncwb.cnncw.cn/shtml/ncwb/20190809/index.shtml/node_1.htm",
          //-----------------------------------
                  "http://www.zyrb.com.cn/",
                  "http://np.jj831.com/html/{year}-{month2}/{day2}/node_2.htm",
                  "http://epaper.ybwb.cn/",
          //-----------------------------------
                  "http://www.jj831.com/",
                  "http://www.ybxww.com/",
                  "http://ncrb.cnncw.cn/index.shtml",
                  "http://www.cnncw.cn",*/
          //-----------------------------------
                  "http://ncwb.cnncw.cn/shtml/ncwb/{year}{month2}{day2}/index.shtml",
                  "http://www.dzrbs.com/dzrbspage/dzrb/html/{year}-{month2}/{day2}/node_3.htm",
                  "http://www.dzrbs.com/",
          //-----------------------------------
                  "http://www.dzrbs.com/dzrbspage/dzwb/html/{year}-{month2}/{day2}/node_19.htm",
                  "http://epaper.beiww.com/yarb/pc/navigation_005001001/{year}/{month2}/{day2}/001.html",
                  "http://www.dayaw.cn/",
          //-----------------------------------
                  "http://www.beiww.com/",
                  "http://szb.gazx.org/pc/column/201902/26/node_01.html",
                  "http://www.gazx.org/",
          //-----------------------------------
                  "http://www.gatv.com.cn/",
//                  "/",
//                  "/",
          //-----------------------------------
                  "http://www.bznews.org/",
                  "http://szb.mshw.net/html/2019-08/26/node_2.htm",
                  "http://www.mshw.net/",
          //-----------------------------------
                  "http://www.dpwhw.net/"
          //-----------------------------------

  };
  //底页（详情页链接）提取规则
  private String[] detailLinkRule={
//          "http://ncwb.cnncw.cn/shtml/ncwb/{year}{month2}{day2}/v\\w*.shtml@http://ncwb.cnncw.cn/shtml/ncwb/{year}{month2}{day2}/\\d+.shtml",
//          "http://www.dzrbs.com/dzrbspage/dzrb/html/{year}-{month2}/{day2}/node_\\d+.htm@http://www.dzrbs.com/dzrbspage/dzrb/html/{year}-{month2}/{day2}/content_\\d+.htm",
//          "http://www.dzrbs.com/html/{year}-{month2}/{day2}/content_\\d+.html",
//          //-----------------------------------
//          "http://www.dzrbs.com/dzrbspage/dzwb/html/{year}-{month2}/{day2}/node_\\d+.htm@http://www.dzrbs.com/dzrbspage/dzwb/html/{year}-{month2}/{day2}/content_\\d+.htm",
//          "http://epaper.beiww.com/yarb/pc/navigation_005001001/{year}/{month2}/{day2}/\\d+.html@http://epaper.beiww.com/yarb/pc/navigation_005001001/{year}/{month2}/{day2}/\\d+/\\d+.html",
//          "http://www.dayaw.cn/news/\\w+/{year}/{month2}{day2}/\\d+.html",
//          //-----------------------------------
//          "http://zyrb.com.cn/{year}/{month2}{day2}/\\d+.shtml",
//          "http://np.jj831.com/html/{year}-{month2}/{day2}/node_\\d+.htm@http://np.jj831.com/html/{year}-{month2}/{day2}/content_\\d+.htm",
//          "http://epaper.ybwb.cn/content/{year}-{month2}/{day2}/\\w*@http://epaper.ybwb.cn/content/{year}-{month2}/{day2}/\\d+.html",
//          //-----------------------------------
//          "http://www.jj831.com/{year}/{month2}{day2}/\\d+.shtml",
//          "http://www.ybxww.com/\\w*/html/{year}{month2}/\\d+.shtml",
//          "http://ncrb.cnncw.cn/shtml/ncrb/{year}{month2}{day2}/vA\\d+.shtml",
//          "http://www.cnncw.cn/{year}/{month2}{day2}/\\d+.shtml",



          "http://ncwb.cnncw.cn/shtml/ncwb/{year}{month2}{day2}/v\\w+.shtml@http://ncwb.cnncw.cn/shtml/ncwb/{year}{month2}{day2}/\\d+.shtml",
          "http://www.dzrbs.com/dzrbspage/dzrb/html/{year}-{month2}/{day2}/node_\\d+.htm@http://www.dzrbs.com/dzrbspage/dzrb/html/{year}-{month2}/{day2}/content_\\d+.htm",
          "http://www.dzrbs.com/html/{year}-{month2}/{day2}/content_\\d+.html",
          //-----------------------------------
          "http://www.dzrbs.com/dzrbspage/dzwb/html/{year}-{month2}/{day2}/node_\\d+.htm@http://www.dzrbs.com/dzrbspage/dzwb/html/{year}-{month2}/{day2}/content_\\d+.htm",
          "http://epaper.beiww.com/yarb/pc/navigation_005001001/{year}/{month2}/{day2}/\\d+.html@http://epaper.beiww.com/yarb/pc/navigation_005001001/{year}/{month2}/{day2}/\\d+/\\d+.html",
          "http://www.dayaw.cn/news/\\w*/{year}/{month2}{day2}/\\d+.html",
          //-----------------------------------
          "http://news.beiww.com/yayw1763/{year}{month2}/t{year}{month2}{day2}_\\d+.html",
          "http://szb.gazx.org/pc/column/{year}{month2}/{day2}/node_\\d+.html@http://szb.gazx.org/pc/content/{year}{month2}/{day2}/content_\\d+.html",
          "http://www.gazx.org/content/{year}-{month2}/{day2}/content_\\d+.html",
          //-----------------------------------
          "http://www.gatv.com.cn/1/\\d+_1.shtml",
//          "",
//          "",

          //-----------------------------------
          "http://www.bznews.org/news/\\w*/{year}{month2}/\\d+.html",
          "http://szb.mshw.net/html/{year}-{month2}/{day2}/node_\\d+.htm@http://szb.mshw.net/html/{year}-{month2}/{day2}/content_\\d+.htm",
          "http://www.mshw.net/xwzx/\\w*/{year}{month2}/t{year}{month2}{day2}_\\d+.html",
          "http://dpwh.mshw.net/\\w*/{year}{month2}/t{year}{month2}{day2}_\\d+.html",



  };
  //详情页标题提取规则
  private String[] titleRule={
//          "#content > h1",
//          ".font01",
//          "#content_head > h1",
//          //-----------------------------------
//          ".font01",
//          ".detail-title-box > h3",
//          ".article-body > h1",
//          //-----------------------------------
//          "#c1",
//          ".font01",
//          ".newsdetail_bg.clearfix > h1",
//          //-----------------------------------
//          ".text-center",
//          ".h-title",
//          "#content > h5:nth-child(5)",
//          ".column.article-content.js-returntop.pos-r > h1",



          "#content > h1",
          ".font01",
          "#content_head > h1",
          //-----------------------------------
          ".font01",
          ".detail-title-box > h3",
          ".article-body > h1",
          //-----------------------------------
          ".ya-xl-top > h1",
          "#Title",
          ".content_tit",
          //-----------------------------------
          ".page > div.left.cont > h1",
//          "",
//          "",
          //-----------------------------------
          "#titleContent",
          ".title1",
          ".vvmi-left-ti.lf > h1",
          ".dp-atr > p:nth-child(1)",

  };
//  //author
//  private String[] authors={
//          "",
//          "",
//          "#content_head > div > div:nth-child(5) > span",
//          //-----------------------------------
//          "",
//          "",
//          ".user",
//          //-----------------------------------
//          "#b1 > div:nth-child(8) > p",
//          "",
//          "",
//          //-----------------------------------
//          ".article-info > span:nth-child(2)",
//          ".zuozhe",
//          "",
//          "",
//
//  };
  //详情页内容提取规则
  private String[] contentRule={
          "#content_div",
          "#ozoom",
          "#endtext",
          //-----------------------------------
          "#ozoom",
          "#DETAIL_CONTENT > div",
          "#article-content",
          //-----------------------------------
          ".clearfix > div.ya-xl-con",
          "#ozoom",
          ".c_left.fl.mr30 > div.con_detail",
          //-----------------------------------
          ".left.cont > div.content",
//          "",
//          "",
          //-----------------------------------
          "#tLWPage_content_left > div.cotentBox",
          ".content_right",
          "#font",
          ".dp-atr > div.dp-atr-content",

  };


  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addNews() throws InterruptedException {
    // 抓站管理的网页
    driver.get("http://pmop.staff.ifeng.com/Cmpp/develop/index.jhtml?nodeId=12006");
    //凤凰令牌
    driver.findElement(By.id("txtVerifyCode")).sendKeys(ids.toString());
    // 点击确定按钮
    driver.findElement(By.xpath("//*[@id='x-form-el-txtVerifyCode']/span/button")).click();//*[@id="x-form-el-txtVerifyCode"]/span

    // 2 | setWindowSize | 945x1020 |  |
    driver.manage().window().setSize(new Dimension(1920, 1080));
    Thread.sleep(2000);


    // 打开左侧抓站任务表
    driver.findElement(By.id("extdd-24")).click();
    Thread.sleep(1000);
    //选择抓站任务表的frame
    driver.switchTo().frame("centerTabPanel__tab_fdf08cf9c87777b9b5a472cdf0c52354");
    // 点击列表视图的打开按钮
    driver.findElement(By.id("ext-gen153")).click();
    Thread.sleep(1000);

    // 选择列表视图页面的frame
    driver.switchTo().defaultContent();
    driver.switchTo().frame("centerTabPanel__tab_ba233b934f455dabf0673a5d1d9de47c");
    // 点击增加按钮
    driver.findElement(By.id("ext-gen141")).click();
    Thread.sleep(1000);

    for (int i=0;i<num;i++){
      // 选择增加页面的frame
      driver.switchTo().defaultContent();
      driver.switchTo().frame("centerTabPanel__tab_list_add_23133_15414");

      // TextField_2 |媒体名称| 安徽商报 |
      driver.findElement(By.id("TextField_2")).click();
      driver.findElement(By.id("TextField_2")).sendKeys(mediaName[i]);

      //TextField_39 | 媒体id| 初始值10005 |
      driver.findElement(By.id("TextField_39")).click();
      driver.findElement(By.id("TextField_39")).sendKeys(ids.toString());
      ids++;

      // ComboBox_45 | 类别 | //*[@id="ext-gen6"]
      driver.findElement(By.id("ComboBox_45")).click();//*[@id='x-form-el-txtVerifyCode']/span/button
      // ext-gen479 | 稿源 | 这个js动态生成只能定位到具体标签//*[@id="ext-gen6"]/div[3]/div[1]/div[3]
      driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[3]/div[1]/div[3]")).click();

      // 同步地址 | 稿源 | 这个js动态生成只能定位到具体标签//*[@id="CheckboxGroup_37"]
      driver.findElement(By.xpath("//*[@id=\"x-form-el-CheckboxGroup_37\"]/span/span/input")).click();

      // TextField_3 | 抓取地址 | 爬取的网站{year}{month2}/{day2}
      driver.findElement(By.id("TextField_3")).click();
      driver.findElement(By.id("TextField_3")).sendKeys(url[i]);

      // ComboBox_25 | 抓取周期
      driver.findElement(By.id("ComboBox_25")).click();
      // 30min | 这个js动态生成id只能定位到具体标签//*[@id="ext-gen6"]/div[3]
      driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[4]/div[1]/div[3]")).click();

      // ComboBox_5 | 状态
      driver.findElement(By.id("ComboBox_5")).click();
      // 上线不同步 | 这个js动态生成id只能定位到具体标签
      driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[5]/div[1]/div[8]")).click();

      // ComboBox_4 | 首页解析方式
      driver.findElement(By.id("ComboBox_4")).click();
      // html | 这个js动态生成id只能定位到具体标签
      driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[6]/div[1]/div[1]")).click();

      // ComboBox_7 | 底页解析方式
      driver.findElement(By.id("ComboBox_7")).click();
      // css | 这个js动态生成id只能定位到具体标签
      driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[7]/div[1]/div[2]")).click();

      // TextField_8 | 底页(详情页链接)提取规则:
      // detailLinkRule[]
      driver.findElement(By.id("TextField_8")).click();
      driver.findElement(By.id("TextField_8")).sendKeys(detailLinkRule[i]);

      // TextField_12 | 详情页标题规则
      driver.findElement(By.id("TextField_12")).click();
      driver.findElement(By.id("TextField_12")).sendKeys(titleRule[i]);

      // TextField_14 | 详情页日期提取
      driver.findElement(By.id("TextField_14")).click();
      driver.findElement(By.id("TextField_14")).sendKeys("auto");

      // TextField_15 | 抓取几日内
      driver.findElement(By.id("TextField_15")).click();
      driver.findElement(By.id("TextField_15")).sendKeys("2");

      // TextField_16 | 详情页来源规则
      driver.findElement(By.id("TextField_16")).click();
      driver.findElement(By.id("TextField_16")).sendKeys("auto");

//      // TextField_16 | 详情页来源规则
//      driver.findElement(By.id("TextField_22")).click();
//      driver.findElement(By.id("TextField_22")).sendKeys(authors[i]);

      //TextField_23 | 详情页内容规则
      driver.findElement(By.id("TextField_23")).click();
      driver.findElement(By.id("TextField_23")).sendKeys(contentRule[i]);

      //点击保存
      driver.findElement(By.xpath("//*[@id=\"btn_b_saveAndAdd\"]/tbody/tr/td[2]")).click();
      Thread.sleep(2000);
    }
  }
}
