// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class AddNewsTest {
  private WebDriver driver;
  private Map<String, Object> vars;

  //媒体名称
  private String[] mediaName={};
  //媒体ID
  private Integer ids=111;
  //json
  private String[] json={};
  //网站url
  private String[] url={};
  //底页（详情页链接）提取规则
  private String[] detailLinkRule={};
  //详情页标题提取规则
  private String[] titleRule={};
  //详情页内容提取规则
  private String[] contentRule={};
  //

  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addNews() throws InterruptedException {
    // 抓站管理的网页
    driver.get("http://pmop.staff.ifeng.com/Cmpp/develop/index.jhtml?nodeId=12006");
    //凤凰令牌
    driver.findElement(By.id("txtVerifyCode")).sendKeys("196006");
    // 点击确定按钮
    driver.findElement(By.xpath("//*[@id='x-form-el-txtVerifyCode']/span/button")).click();//*[@id="x-form-el-txtVerifyCode"]/span

    // 2 | setWindowSize | 945x1020 |  |
    driver.manage().window().setSize(new Dimension(1920, 1080));
    Thread.sleep(2000);


    // 打开左侧抓站任务表
    driver.findElement(By.id("extdd-24")).click();
    Thread.sleep(1000);
    //选择抓站任务表的frame
    driver.switchTo().frame("centerTabPanel__tab_fdf08cf9c87777b9b5a472cdf0c52354");
    // 点击列表视图的打开按钮
    driver.findElement(By.id("ext-gen153")).click();
    Thread.sleep(1000);

    // 选择列表视图页面的frame
    driver.switchTo().defaultContent();
    driver.switchTo().frame("centerTabPanel__tab_ba233b934f455dabf0673a5d1d9de47c");
    // 点击增加按钮
    driver.findElement(By.id("ext-gen141")).click();
    Thread.sleep(1000);
    for (int i=0;i<5;i++){
    // 选择增加页面的frame
    driver.switchTo().defaultContent();
    driver.switchTo().frame("centerTabPanel__tab_list_add_23133_15414");

    // TextField_2 |媒体名称| 安徽商报 |
    //mediaName[]
    driver.findElement(By.id("TextField_2")).click();
    driver.findElement(By.id("TextField_2")).sendKeys("安徽商报");

    //TextField_39 | 媒体id| 初始值10002 |
    driver.findElement(By.id("TextField_39")).click();
    ids++;
    String id=ids.toString();
    driver.findElement(By.id("TextField_39")).sendKeys(id);

    // ComboBox_45 | 类别 | //*[@id="ext-gen6"]
    driver.findElement(By.id("ComboBox_45")).click();//*[@id='x-form-el-txtVerifyCode']/span/button
    // ext-gen479 | 稿源 | 这个js动态生成只能定位到具体标签//*[@id="ext-gen6"]/div[3]/div[1]/div[3]
    driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[3]/div[1]/div[3]")).click();

    // TextField_42 | 配置json | {"id":"10002","name":"安徽商报"}
    //json[]
    driver.findElement(By.id("TextField_42")).click();
    driver.findElement(By.id("TextField_42")).sendKeys("{\"id\":\"10002\",\"name\":\"安徽商报\"}");

    // 同步地址 | 稿源 | 这个js动态生成只能定位到具体标签//*[@id="CheckboxGroup_37"]
    driver.findElement(By.xpath("//*[@id=\"x-form-el-CheckboxGroup_37\"]/span/span/input")).click();

    // TextField_3 | 抓取地址 | 爬取的网站{year}{month2}/{day2}
    //url[]
    driver.findElement(By.id("TextField_3")).click();
    driver.findElement(By.id("TextField_3")).sendKeys("http://epaper.anhuinews.com/html/ahsb.shtml");

    // ComboBox_25 | 抓取周期
    driver.findElement(By.id("ComboBox_25")).click();
    // 30min | 这个js动态生成id只能定位到具体标签//*[@id="ext-gen6"]/div[3]
    driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[4]/div[1]/div[3]")).click();

    // ComboBox_5 | 状态
    driver.findElement(By.id("ComboBox_5")).click();
    // 上线不同步 | 这个js动态生成id只能定位到具体标签

    driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[5]/div[1]/div[8]")).click();

    // ComboBox_4 | 首页解析方式
    driver.findElement(By.id("ComboBox_4")).click();
    // html | 这个js动态生成id只能定位到具体标签
    driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[6]/div[1]/div[1]")).click();

    // ComboBox_7 | 底页解析方式
    driver.findElement(By.id("ComboBox_7")).click();
    // css | 这个js动态生成id只能定位到具体标签
    driver.findElement(By.xpath("//*[@id=\"ext-gen6\"]/div[7]/div[1]/div[2]")).click();

    // TextField_8 | 底页(详情页链接)提取规则:
    // detailLinkRule[]
    driver.findElement(By.id("TextField_8")).click();
    driver.findElement(By.id("TextField_8")).sendKeys("http://news.yznews.com.cn.*/content_\\d+.htm");

    // TextField_12 | 详情页标题规则
    // titleRule[i]
    driver.findElement(By.id("TextField_12")).click();
    driver.findElement(By.id("TextField_12")).sendKeys(".paper_nr.zww > h1");

    // TextField_14 | 详情页日期提取
    driver.findElement(By.id("TextField_14")).click();
    driver.findElement(By.id("TextField_14")).sendKeys("auto");

    // TextField_15 | 抓取几日内
    driver.findElement(By.id("TextField_15")).click();
    driver.findElement(By.id("TextField_15")).sendKeys("2");

    // TextField_16 | 详情页来源规则
    driver.findElement(By.id("TextField_16")).click();
    driver.findElement(By.id("TextField_16")).sendKeys("auto");

    //TextField_23 | 详情页内容规则
    driver.findElement(By.id("TextField_23")).click();
    driver.findElement(By.id("TextField_23")).sendKeys(".paper_nr.zww > div");

    //TextField_23 | 详情页内容规则
    driver.findElement(By.xpath("//*[@id=\"btn_b_saveAndAdd\"]/tbody/tr/td[2]")).click();
    Thread.sleep(2000);

   }
  }
}
