// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;
public class WechatEntering {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  //微信名称
  String[] names={

         "四川日报","四川农村日报","华西都市报",
          "文摘周报","天府早报","金融投资报",
          "四川在线","成都日报","成都商报",
          //-----------------------------------------
          "先锋","公司","青年作家",
          "时代教育", "新城快报", "每日经济新闻",
          "成都晚报", "成都女报", "四川新闻网",
          //-----------------------------------------
          "绵阳日报", "绵阳新闻网", "绵阳晚报",
          "自贡日报", "自贡网", "自贡晚报",
          "攀枝花日报", "攀枝花新闻网", "攀枝花晚报",
          //-----------------------------------------
          "泸州日报", "泸州晚报", "泸州新闻网",
          "德阳日报", "德阳网", "德阳晚报",
          "广元日报", "广元晚报", "广元新闻网",
          //-----------------------------------------
          "遂宁日报", "遂宁晚刊", "遂宁在线",
          "遂宁宣传", "遂宁新闻网", "内江日报",
          "内江晚报", "内江新闻网", "乐山日报",
          //-----------------------------------------
          "三江都市报", "乐山新闻网", "资阳日报",
          "资阳网", "宜宾日报", "宜宾晚报",
          "金江网", "宜宾新闻网", "南充日报",
          //-----------------------------------------
          "南充新闻网", "南充晚报", "达州日报",
          "达州日报网", "达州晚报", "雅安日报",
          "大雅网", "北纬网", "广安日报",
          //-----------------------------------------
          "广安在线", "广安新闻网", "巴中日报",
          "巴中晚报", "巴中传媒网", "眉山日报",
          "眉山网", "东坡文化网",
  };
  //微信号
  String[] ids={

          /*"xarbwx","xawbblt","gh_bae2c0ea20cd",
          "xianwzw","xdbjbok","ddnbgzh",
          "sanqinwx","CYCG668","isxdaily",
          //-----------------------------------------
          "sxncb1953","xibufazhibao","fcgzwx","gh_75cae67b5465","hsb88880000",
          "isxcmw","hsw_news",
          "tongchuanribao","wntvwnxw","zhangshangweinan",
          //-----------------------------------------
          "hswnet","jrwnweb","yadaily",
          "gh_6a2c549fddbf","ylrbwx",*/"ylzk2014",
          "hzrb0916","slrb_xmt","a-k-r-b","AKTV2869130841",
          //-----------------------------------------
          "slxw01","baojinews","v_baoji "
  };
  //选择页面框架，每次都会+2
  private int num=1;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demo() throws InterruptedException {
    // 微信录入的网站
    driver.get("http://10.90.3.38:8086/spider-admin/login");
    // 设置页面
    driver.manage().window().setSize(new Dimension(1920, 1080));
    //  click | name=username |  |
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("yangzj3");
    //  click | name=password |  |
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123321");
    //  click | 登陆按钮
    driver.findElement(By.cssSelector(".btn")).click();


    //  click | linkText=抓站管理
    Thread.sleep(2000);
    driver.findElement(By.linkText("抓站管理")).click();
    //  click | linkText=抓取站点列表
    Thread.sleep(2000);
    driver.findElement(By.linkText("抓取站点列表")).click();

    for(int i=0;i<names.length;i++){

      // 选择页面框架 | click | 添加
      Thread.sleep(1000);
      driver.switchTo().frame("iframe5");
      driver.findElement(By.cssSelector("#WeMediaAccountNewTableToolbar > .btn:nth-child(1)")).click();

      // 选择添加页面框架
      driver.switchTo().frame("layui-layer-iframe"+num);
      num+=2;

      //  click | 站点id | label=稿源--微信
      driver.findElement(By.id("siteId")).click();
      {
        WebElement dropdown = driver.findElement(By.id("siteId"));
        dropdown.findElement(By.xpath("//option[. = '67:稿源--微信']")).click();
      }

      // click | 来源类型 | label=微信 |
      driver.findElement(By.id("fromType")).click();
      {
        WebElement dropdown = driver.findElement(By.id("fromType"));
        dropdown.findElement(By.xpath("//option[. = '微信']")).click();
      }


      // click | 抓取时间周期 | label=1440min |
      driver.findElement(By.id("cycle")).click();
      {
        WebElement dropdown = driver.findElement(By.id("cycle"));
        dropdown.findElement(By.xpath("//option[. = '1440min']")).click();

      }

      //  click | 状态 | label=正常 |
      driver.findElement(By.id("status")).click();
      {
        WebElement dropdown = driver.findElement(By.id("status"));
        dropdown.findElement(By.xpath("//option[. = '正常']")).click();
      }

//      driver.findElement(By.id("status")).click();

      //click | 抓取几日内 | 2 |
      driver.findElement(By.id("beforeDate")).click();
      driver.findElement(By.id("beforeDate")).sendKeys("2");

      // click | 内容格式 | label=全部 |
      driver.findElement(By.id("shape")).click();
      {
        WebElement dropdown = driver.findElement(By.id("shape"));
        dropdown.findElement(By.xpath("//option[. = '全部']")).click();
      }

      //  click | 数据流处 | 持久化 |
      driver.findElement(By.name("pageProcessName")).click();

      //  click | 媒体名称 | 微信名称 |
      driver.findElement(By.id("nickName")).click();
      driver.findElement(By.id("nickName")).sendKeys(names[i]);

      //click | 用户id | 微信号 |
      driver.findElement(By.id("userId")).click();
      driver.findElement(By.id("userId")).sendKeys(ids[i]);

      //click | 提交 |  |
      driver.findElement(By.id("ensure")).click();
    }
  }
}
