// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class WechatEntering {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  String[] names={"j","2"};
  String[] ids={"j","2"};

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void demo() throws InterruptedException {
    // Test name: Login
    // Step # | name | target | value | comment
    // 1 | open | http://10.90.3.38:8086/spider-admin/login |  |
    driver.get("http://10.90.3.38:8086/spider-admin/login");
    // 2 | setWindowSize | 945x1020 |  |
    driver.manage().window().setSize(new Dimension(1920, 1080));
    // 3 | click | name=username |  |
    driver.findElement(By.name("username")).click();
    // 4 | type | name=username | yangzj3 |
    driver.findElement(By.name("username")).sendKeys("yangzj3");
    // 5 | click | name=password |  |
    driver.findElement(By.name("password")).click();
    // 6 | type | name=password | 123321 |
    driver.findElement(By.name("password")).sendKeys("123321");
    // 7 | click | css=.btn |  |
    driver.findElement(By.cssSelector(".btn")).click();


    // 3 | click | linkText=抓站管理 |  |
    Thread.sleep(2000);
    driver.findElement(By.linkText("抓站管理")).click();
    // 4 | click | linkText=抓取站点列表 |  |
    Thread.sleep(2000);
    driver.findElement(By.linkText("抓取站点列表")).click();

    //加入循环！！！！
    for(int i=0;i<names.length;i++){
      // 5 | selectFrame | index=2 |  |
      Thread.sleep(1000);
      driver.switchTo().frame("iframe5");
      // 6 | click | css=#WeMediaAccountNewTableToolbar > .btn:nth-child(1) |  |
      driver.findElement(By.cssSelector("#WeMediaAccountNewTableToolbar > .btn:nth-child(1)")).click();
      // 7 | selectFrame | index=1 |  |
      driver.switchTo().frame("layui-layer-iframe1");
      // 8 | click | id=siteId |  |
      driver.findElement(By.id("siteId")).click();
      // 9 | select | id=siteId | label=67:稿源--微信 |
      {
        WebElement dropdown = driver.findElement(By.id("siteId"));
        dropdown.findElement(By.xpath("//option[. = '67:稿源--微信']")).click();
      }
      // 11 | click | id=fromType |  |
      driver.findElement(By.id("fromType")).click();
      // 12 | select | id=fromType | label=微信 |
      {
        WebElement dropdown = driver.findElement(By.id("fromType"));
        dropdown.findElement(By.xpath("//option[. = '微信']")).click();
      }
      // 13 | click | id=fromType |  |
      driver.findElement(By.id("fromType")).click();
      // 14 | click | id=cycle |  |
      driver.findElement(By.id("cycle")).click();
      // 15 | select | id=cycle | label=1440min |
      {
        WebElement dropdown = driver.findElement(By.id("cycle"));
        dropdown.findElement(By.xpath("//option[. = '1440min']")).click();
      }
      // 16 | click | id=cycle |  |
      driver.findElement(By.id("cycle")).click();
      // 17 | click | id=status |  |
      driver.findElement(By.id("status")).click();
      // 18 | select | id=status | label=正常 |
      {
        WebElement dropdown = driver.findElement(By.id("status"));
        dropdown.findElement(By.xpath("//option[. = '正常']")).click();
      }
      // 19 | click | id=status |  |
      driver.findElement(By.id("status")).click();
      // 20 | click | id=beforeDate |  |
      driver.findElement(By.id("beforeDate")).click();
      // 21 | type | id=beforeDate | 2 |
      driver.findElement(By.id("beforeDate")).sendKeys("2");
      // 22 | click | id=shape |  |
      driver.findElement(By.id("shape")).click();
      // 23 | select | id=shape | label=全部 |
      {
        WebElement dropdown = driver.findElement(By.id("shape"));
        dropdown.findElement(By.xpath("//option[. = '全部']")).click();
      }
      // 24 | click | id=shape |  |
      driver.findElement(By.id("shape")).click();
      // 25 | click | name=pageProcessName |  |
      driver.findElement(By.name("pageProcessName")).click();
      // 26 | click | id=nickName |  |
      driver.findElement(By.id("nickName")).click();
      // 27 | type | id=nickName | 安徽网 |
      driver.findElement(By.id("nickName")).sendKeys(names[0]);
      // 28 | click | id=userId |  |
      driver.findElement(By.id("userId")).click();
      // 29 | type | id=userId | ahwangwx |
      driver.findElement(By.id("userId")).sendKeys(ids[0]);
      // 30 | click | id=ensure |  |
      driver.findElement(By.id("ensure")).click();
    }
  }
}
